# Generated by Django 2.2 on 2019-12-28 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('c1', models.CharField(max_length=400)),
                ('c2', models.CharField(max_length=400)),
                ('c3', models.CharField(max_length=400)),
                ('c4', models.CharField(max_length=400)),
                ('correct_choice_Id', models.IntegerField(default=1, validators=[django.core.validators.RegexValidator(message='You should Choice number between 1 to 4 only', regex='^[1-4]$')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('answers', models.CharField(default='', max_length=500)),
                ('score', models.FloatField(default=0)),
                ('questions', models.ManyToManyField(to='pages.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.User')),
            ],
        ),
    ]
