# Generated by Django 2.2 on 2019-12-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='correct_choice_Id',
            new_name='correct_choice_id',
        ),
    ]
